services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab' 
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

  minio:
    image: minio/minio:latest
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: tyucvb1620
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - gitlab-network

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tyucvb1620
      POSTGRES_DB: for_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config:/etc/gitlab-runner
    networks:
      - gitlab-network
    depends_on:
      - gitlab

volumes:
  pgdata:

networks:
  gitlab-network:
    driver: bridge